# Generated by Django 2.1.15 on 2020-08-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Devicetag',
        ),
    ]
