# Generated by Django 2.1.15 on 2020-08-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200819_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicetag',
            old_name='name',
            new_name='device_type',
        ),
    ]
