# Generated by Django 2.1.15 on 2020-08-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='loc_id',
            field=models.IntegerField(),
        ),
    ]
