# Generated by Django 2.1.15 on 2020-08-19 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200819_2041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devicetag',
            new_name='Device',
        ),
    ]
