# Generated by Django 2.1.15 on 2020-08-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200819_2253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Device',
            new_name='Devicetype',
        ),
    ]
