# Generated by Django 2.1.15 on 2020-08-20 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200820_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wxstatreading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('air_temp', models.FloatField(null=True)),
                ('humidity', models.FloatField(null=True)),
                ('wind_avg_spd_kph', models.FloatField(null=True)),
                ('wind_avg_direct', models.FloatField(null=True)),
                ('wind_std_dev', models.IntegerField(null=True)),
                ('rain_mm', models.FloatField(null=True)),
                ('soil_temp', models.FloatField(null=True)),
                ('barometric', models.FloatField(null=True)),
                ('evaporation', models.FloatField(null=True)),
                ('air_temp_10_m', models.FloatField(null=True)),
                ('air_temp_inversion', models.CharField(max_length=20, null=True)),
                ('wind_direction_1', models.CharField(max_length=20, null=True)),
                ('wind_direction_2', models.CharField(max_length=20, null=True)),
                ('wind_dir_1_percent', models.IntegerField(null=True)),
                ('wind_dir_2_percent', models.IntegerField(null=True)),
                ('wind_speed_max', models.FloatField(null=True)),
                ('wind_speed_min', models.FloatField(null=True)),
                ('wind_speed_avg', models.FloatField(null=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Device')),
            ],
        ),
        migrations.RemoveField(
            model_name='devicetype',
            name='user',
        ),
        migrations.AddField(
            model_name='wxstatreading',
            name='device_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Devicetype'),
        ),
        migrations.AddField(
            model_name='wxstatreading',
            name='loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Location'),
        ),
        migrations.AddField(
            model_name='wxstatreading',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Devicetype'),
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
