# Generated by Django 2.1.15 on 2020-08-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200820_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wxstatreading',
            name='device_type',
        ),
    ]
