# Generated by Django 2.1.15 on 2020-08-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_wxstatreading_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxstatreading',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
