# Generated by Django 2.1.15 on 2020-08-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200820_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raingaugereading',
            old_name='device',
            new_name='device_id',
        ),
        migrations.RenameField(
            model_name='raingaugereading',
            old_name='loc',
            new_name='loc_id',
        ),
        migrations.RemoveField(
            model_name='raingaugereading',
            name='user',
        ),
        migrations.AddField(
            model_name='raingaugereading',
            name='loc_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='raingaugereading',
            name='system_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
