# Generated by Django 2.1.15 on 2020-08-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200821_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raingaugereading',
            old_name='loc_id',
            new_name='LocationID',
        ),
    ]
