# Generated by Django 2.1.15 on 2020-08-21 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200821_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raingaugereading',
            old_name='accum_rain',
            new_name='AccumulatedRain',
        ),
        migrations.RenameField(
            model_name='raingaugereading',
            old_name='loc_name',
            new_name='LocationDescription',
        ),
        migrations.RenameField(
            model_name='raingaugereading',
            old_name='system_type',
            new_name='SystemType',
        ),
        migrations.RenameField(
            model_name='raingaugereading',
            old_name='device_id',
            new_name='deviceID',
        ),
    ]
