# Generated by Django 2.1.15 on 2020-08-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200824_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soilprobereading',
            old_name='loc',
            new_name='LocationID',
        ),
        migrations.RenameField(
            model_name='soilprobereading',
            old_name='device',
            new_name='deviceID',
        ),
        migrations.RemoveField(
            model_name='soilprobereading',
            name='user',
        ),
        migrations.AddField(
            model_name='soilprobereading',
            name='LocationDescription',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='soilprobereading',
            name='SystemType',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
